name: tae
checkpoint: False
representation: backbone_coordinate
input_dim: 30
model: {
  encoder_layers: [30, 100, 100, 1],
  options: {
    encoder: {
      activation: "tanh",
      dropout: [0.5, 0.5, 0.5]
    },
    decoder: {
      activation: "tanh"
    },
    norm_in: {
    }
  }
}
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.01,
    patience: 50
  }
  batch_size: 2000
  max_epochs: 1000
logger:
  name: wandb
  project: mlcv
  log_model: False
  tags:
  - baseline
