molecule: alanine
start_state: c5
goal_state: c7ax
repeat: 2
sample_num: 64
simulation:
  k: 100
  time_horizon: 1000
  force_version: v1
  friction: 0.001
  timestep: 1
  force_field: ["amber99sbildn.xml", "tip3p.xml"]
  temperature: 300
  platform: OpenCL
  precision: mixed