name: autoencoder
input_dim: 24
model: {
  encoder_layers: [24, 40, 2],
  options: {
    encoder: {
      activation: "tanh"
    },
    decoder: {
      activation: "tanh"
    },
    norm_in: {
    }
  }
}
data:
  dir: /home/shpark/prj-cmd/data
  molecule: alanine
  temperature: 300.0
  version: da-1n-v1
  input: coordinate
  atom: 22
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.1,
    patience: 50
  }
  max_epochs: 2000
  logger:
    name: wandb
    project: clcv-baseline
    log_model: False
    tags:
    - baseline