name: clcv
input_dim: 45
model: {
  encoder_layers: [45, 40, 40, 2],
  options: {
    encoder: {
      activation: "tanh"
    },
    norm_in: {
    }
  }
}
data:
  dir: /home/shpark/prj-cmd/data
  molecule: alanine
  temperature: 300.0
  version: cl-10n-v3
  input: coordinate
  atom: 22
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.01,
    patience: 100
  }
  max_epochs: 1000
  logger:
    name: wandb
    project: clcv-baseline
    log_model: False
    tags:
    - method