name: deeptda
input_dim: 45
output_scale: 7
model: {
  n_states: 2,
  n_cvs: 1,
  target_centers: [-7, 7],
  target_sigmas: [0.2, 0.2],
  layers: [45, 24, 12, 1],
  options: {
    norm_in: {
    },
    nn: {
      activation: "relu"
    },
  },
}
data:
  dir: ../simulation/dataset
  molecule: alanine
  temperature: 300.0
  version: 1n-v1
  input: distance
  atom: 22
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.1,
    patience: 50
  }
  max_epochs: 2000
  logger:
    name: wandb
    project: clcv-baseline
    log_model: False
    tags:
    - baseline