name: timelagged-autoencoder
input_dim: 30
model: {
  encoder_layers: [30, 100, 100, 1],
  options: {
    encoder: {
      activation: "tanh",
      dropout: [0.5, 0.5, 0.5]
    },
    decoder: {
      activation: "tanh"
    },
    norm_in: {
    }
  }
}
data:
  dir: /home/shpark/prj-cmd/data
  molecule: alanine
  temperature: 300.0
  version: timelag-1n-v1
  input: coordinate
  atom: 22
trainer:
  early_stopping: {
    monitor: "valid_loss",
    min_delta: 0.01,
    patience: 50
  }
  logger:
    name: wandb
    project: clcv-baseline
    log_model: False
    tags:
    - baseline
  params: {
    callbacks: ["metrics", "early_stopping"],
    max_epochs: 1000,
    logger: None,
    enable_checkpointing: False
  }